### ISSUE TITLE
Only 4th image being posted

### ISSUE THREAD

**Issue by mgmisiak** [marcomaroni-github/instagram-to-bluesky#28]
When running the simulation, the program correctly identifies all media and where posts need to be truncated. However, when I ran the program for real (https://bsky.app/profile/mattstagram.bsky.social), each Bluesky post only contains the 4th image or video from the Instagram post, as if the rest of the queue is not included in the post blob.

**Comment by straiforos** [comment]
Thank you @mgmisiak, I will look at this and another video upload issue in the test mode this weekend.

**Comment by straiforos** [comment]
There is a max media limit `MAX_IMAGES_PER_POST = 4`.

I will make the simulate configuration consider this and give better warning to the user that some will be truncated per post.

**Comment by straiforos** [comment]
> each Bluesky post only contains the 4th image or video from the Instagram post, as if the rest of the queue is not included in 
the post blob.

I think I misunderstood the issue you're having. After looking through the code I see it is reporting the processed posts and you mentioned it is truncating correctly but not uploading. I will set up a test from my own instagram data.

**Comment by straiforos** [comment]
I've got a fix, its silly, thank you for reporting the issue! Sorry for the trouble @mgmisiak.

**Comment by straiforos** [comment]
#29 addresses the last image being uploaded and not all of them with unit test surrounding the issue so we can avoid it being reintroduced.

**Comment by straiforos** [comment]
@mgmisiak It seems like videos worked alright for you?

I am looking into #22 and encountering even my own test data does not upload correctly. I noticed your account has video.

Trying to narrow down the issue since my profile https://bsky.app/profile/triforce009.bsky.social worked when I first introduced video upload support.

**Comment by mgmisiak** [comment]
Thank you so much!! Glad it had a root cause and I didn’t simply misconfigure it.

And yes, I don’t recall any thrown errors on my video uploads during execution, but I will keep an eye when I clear the account and re-run.

**Comment by marcomaroni-github** [comment]
@mgmisiak can you confirm that it was fixed wih v0.5.0?

**Comment by mgmisiak** [comment]
I'm attempting a rerun, but am currently running into this error:

```
/home/mgmisiak/instagram-to-bluesky-main/node_modules/sharp/lib/input.js:487
  const stack = Error();
                ^

Error: Input file contains unsupported image format
    at Sharp.metadata (/home/mgmisiak/instagram-to-bluesky-main/node_modules/sharp/lib/input.js:487:17)
    at getImageSize (/home/mgmisiak/instagram-to-bluesky-main/dist/image/image.js:99:34)
    at InstagramImageProcessor.processMedia (/home/mgmisiak/instagram-to-bluesky-main/dist/media/processors/InstagramImageProcessor.js:52:60)
    at InstagramImageProcessor.process (/home/mgmisiak/instagram-to-bluesky-main/dist/media/processors/InstagramImageProcessor.js:33:41)
    at InstagramMediaProcessor.process (/home/mgmisiak/instagram-to-bluesky-main/dist/media/processors/InstagramMediaProcessor.js:50:52)
    at main (/home/mgmisiak/instagram-to-bluesky-main/dist/instagram-to-bluesky.js:170:53)
    at /home/mgmisiak/instagram-to-bluesky-main/dist/main.js:5:43
    at Object.<anonymous> (/home/mgmisiak/instagram-to-bluesky-main/dist/main.js:6:3)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)

Node.js v22.11.0
```


At first I wondered if the subtitle .srt files that are occasionally in the media folder were the problem, but clearing them did not resolve the issue. Looking at the stack trace closer, something isn't meshing with the new getImageSize function, but I can't tell specifically what post is at fault.

**Comment by straiforos** [comment]
Thanks for testing that @mgmisiak, we introduced an aspect ratio functionality that seems to have trouble with some file types. 

I added logic in PR #31 to catch the error and log it while letting it run, ideally most instagram posts are square which is the fallback logic.

Once we get that merged and released I would appreciate if you could find the error log that will have `Failed to get image aspect ratio; image path:` that would help me identify the file type we need to add support for.

In the meantime I will run it on my instagram export so I can possibly find it prior.

**Comment by straiforos** [comment]
I can see videos are somehow getting put through that logic.

`[18:08:42.366] [31mERROR[39m (60513): [36mFailed to get image aspect ratio; image path: instagram-triforce09-2025-02-08-HjuDNu1P/media/posts/202004/AQOQzScexujB8Mk7rPa96nGdkrHJvnJ7W_aaAW_WQya2wCBa2e6iZnFCDEEHGhiy2G0ssoDWTw40xcRbn_sWGiVqk7ovXKxpH4Q8_18102577336086147.mp4, error: Error: Input file contains unsupported image format[39m
`

**Comment by mgmisiak** [comment]
The good news: the simulation had no error

The bad news: I don't know if any media is getting processed now

```
[09:30:49.725] INFO (550): Estimated time for real import: 0 hours and 0 minutes
[09:30:49.725] INFO (550): Import finished at 2025-03-04T14:30:49.725Z, imported 119 posts with 0 media
[09:30:49.725] INFO (550): Total import time: 0 hours and 0 minutes
```

**Comment by straiforos** [comment]
I presume that's in simulate mode? 

Did you turn it off and it did not upload anything?

**Comment by straiforos** [comment]
@mgmisiak I noticed my change for capturing the actual count of media uploaded is circumvented in simulate mode. I can modify that. It will upload correctly.

**Comment by mgmisiak** [comment]
@straiforos So it does! You can see the results of the latest run at my original link. Multi-image posts are now there!

Something I notice is due to (I'm sure) ATProto post limitations: posts that contain photo(s) AND video(s) seem to favor only posting the last video in the array. Perhaps if you end up pursuing the splitting capability you can break up the array around these so everything posts and maintains the correct order.

Awesome work though, this is a fantastic tool!

**Comment by straiforos** [comment]
@mgmisiak Yeah mixed media does not play nice right now, I agree it would be good to split the posts so we can support all instagram media exported.

My understanding is only images should work in a mixed postbut maybe its being set as a video post and only capturing the video. I think depending on the order of media types I look for the first one if its an image then assume its all images.

I will work on that split capability next.

**Comment by marcomaroni-github** [comment]
@straiforos #32 merged, @mgmisiak you can verify...

**Comment by mgmisiak** [comment]
@marcomaroni-github Yes, the simulation looks good again.
```
[09:33:11.994] INFO (1138): Estimated time for real import: 0 hours and 15 minutes
[09:33:11.994] INFO (1138): Import finished at 2025-03-05T14:33:11.994Z, imported 119 posts with 278 media
[09:33:11.994] INFO (1138): Total import time: 0 hours and 0 minutes
```

**Comment by straiforos** [comment]
@mgmisiak #33 will enable all posts to migrate. As a warning it will make your post count double or more if you do not clear it all out.

Cheers!

**Comment by mgmisiak** [comment]
@straiforos It works great!! When I ran it the first time, I noticed a couple posts missing, so I went back through the output and noticed it was due to max file size being exceeded. I scaled the offending files, ran it again, and it came out clean. It might be helpful to flag/identify those posts with a warning in simulation so others would know to take a look at them first.

Also, for posterity, this tool was useful for me to wipe the account and keep the post count accurate: https://deleter.shiroyama.us/

**Comment by straiforos** [comment]
@mgmisiak that's great!

Thanks for sharing the post deleter tool.

Were those videos or images since we have resizing functionality I'd be curious if it killed the process or just failed and was logged. 

Thanks for all the feedback!

**Comment by mgmisiak** [comment]
@straiforos There were 3 photos that weighed in at just over 1 MB, and a video over 1 minute that posted with the “video not found” error. I think they preprocessed and then the error hit as it was posting.

Happy to help! I set up this alt to use with Flashes and it’s exactly what I needed; I imagine with more emerging photo/video clients on ATProto, this importer will be even more valuable for those looking to port their stuff over.

**Comment by straiforos** [comment]
@mgmisiak Thanks! 

I'll set up some test cases next week to try and identify those issues.

The video logic in particular if it resizes and it's still too big it will log an error so I wonder if we're hitting the fail safe or if that's not working.
